spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auction_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/auction
          jwk-set-uri: http://localhost:8080/realms/auction/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8080
  realm: auction
  resource: auction-service
  public-client: true
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  admin-username: admin
  admin-password: admin

server:
  port: 8081

logging:
  level:
    root: INFO
    com.kutalev.auction: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.keycloak: DEBUG

jwt:
  secret: your-256-bit-secret-key-here-must-be-longer-than-256-bits
  expiration: 86400000 # 24 hours in milliseconds 